[package]
name = "Painter"
version = "0.1.0"
edition = "2021"

[dependencies]
egui = { version = "0.30.0" }
eframe = { version = "0.30.0" }
serde = { version = "1.0", features = ["derive"] }
serde_json = { version =  "1.0" }